# Generated by Django 4.1.4 on 2022-12-23 05:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f02180d-fe57-44fc-9b45-18d4197a12b7'), primary_key=True, serialize=False),
        ),
    ]
