# Generated by Django 4.1.4 on 2022-12-23 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_reminder_alter_collections_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='total_tasks',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='collections',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1df7a4c3-bd51-4d2c-a16e-fba0d3cebd52'), primary_key=True, serialize=False),
        ),
    ]
